# Generated by Django 3.1 on 2021-02-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='description',
            new_name='image_description',
        ),
    ]
