# Generated by Django 3.1.7 on 2021-03-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume_max',
        ),
    ]
